#install: make get-deps
language: cpp
#script: scons
compiler: gcc
script: make && make test
# uncomment and edit the following line if your project needs to run something other than `rake`:
# # script: bundle exec rspec spec
